;;; pkg-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:


;;;### (autoloads nil "init-packages" "init-packages.el" (25243 56784
;;;;;;  140731 486000))
;;; Generated autoloads from init-packages.el

(autoload 'install-packages "init-packages" "\
Install a list of Emacs packages.
PACKAGES is the list of packages you want to install.

\(fn PACKAGES)" nil nil)

(register-definition-prefixes "init-packages" '("init-"))

;;;***

;;; End of scraped data

(provide 'pkg-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; coding: utf-8-emacs-unix
;; End:

;;; pkg-autoloads.el ends here
